### PR TITLE
[WIP][BREAKING CHANGE] api: Update to Layer 108

### PR DESCRIPTION
**Pull request by aarani**

### CODE REVIEW

**Comment by aarani** [comment]
Needs Testing. 
Password authentication support removed.

**Comment by knocte** [comment]
@aarani good work!

@CheshireCaat hey you might be interested in this, can you help us test it?

@aarani : by the way, as far as I understand, this PR has 2 parts: one which you updated manually, and the other one which you updated automatically via the generator, can you explain how did you do the latter?

**Comment by aarani** [comment]
> @aarani : by the way, as far as I understand, this PR has 2 parts: one which you updated manually, and the other one which you updated automatically via the generator, can you explain how did you do the latter?

Our generators is a little idiot that cause it's generated code to be unusable without manual modifications. for now before that we can fix it all generated codes need to be formatted and it's errors must be fixed manually and as this layer has a lot of changes it breaks the TelegramClient wrapper which I had to fix too

**Comment by knocte** [comment]
@aarani I see, but still, how did you call the generator?

**Comment by aarani** [comment]
> @aarani I see, but still, how did you call the generator?

Nothing crazy, just run "TLGenerator <path_to_json_schema>"

**Comment by knocte** [comment]
> Nothing crazy, just run "TLGenerator <path_to_json_schema>"

And where to get the json schema?

**Comment by aarani** [comment]
> > Nothing crazy, just run "TLGenerator <path_to_json_schema>"
> 
> And where to get the json schema?

Telegram started updating their documentation and is no having the schema json on their website before that you had to extract it from webogram config files

**Comment by knocte** [comment]
are you sure? check the PR 906 of TLSharp

**Comment by aarani** [comment]
> are you sure? check the PR 906 of TLSharp
of course. afaik there is no need to update anything else to use new layers. we need to support mtproto 2.0 but that's story for another day for now just updating the api is enough

**Comment by knocte** [comment]
are you saying that the current schema in https://core.telegram.org/schema/json is only MTProto2.0 compatible and TLSharp/TgSharp is not MTProto2.0 compatible yet?

**Comment by aarani** [comment]
> are you saying that the current schema in https://core.telegram.org/schema/json is only MTProto2.0 compatible and TLSharp/TgSharp is not MTProto2.0 compatible yet?

I'm exactly saying the opposite. It's compatible with both MTProto versions and using it doesn't need any other changes except changes to schema and models

**Comment by knocte** [comment]
> except changes to schema and models

what changes to schema and models?

**Comment by aarani** [comment]
> what changes to schema and models?

changes that I did inside this pull request

**Comment by knocte** [comment]
You mean the changes after running the generator?

**Comment by aarani** [comment]
> You mean the changes after running the generator?

Yup

**Comment by knocte** [comment]
So then the exact instructions are:

- wget https://core.telegram.org/schema/json
- run "TLGenerator.exe json"

right?

**Comment by aarani** [comment]
> So then the exact instructions are:
> 
> * wget https://core.telegram.org/schema/json
> * run "TLGenerator.exe json"
> 
> right?

and fix all the errors that TLGenerator made and change all the legacy requested that are removed from previous layers that will cause TelegramClient.cs to break and change TelegramClient.cs#83 to let telegram know what version of api we're using to communicate

**Comment by knocte** [comment]
> and fix all the errors that TLGenerator made and change all the legacy requested that are removed from previous layers that will cause TelegramClient.cs to break and change TelegramClient.cs#83 to let telegram know what version of api we're using to communicate

I was asking how to just run the generator, not how to fix the mess later (that was already clear).
I'll run it myself anyway to understand these kind of manual changes that need to be done after, thanks.

**Comment by aarani** [comment]
> I was asking how to just run the generator, not how to fix the mess later (that was already clear).
> I'll run it myself anyway to understand these kind of manual changes that need to be done after, thanks.

I was describing the protocol, sure you're welcome

**Comment by knocte** [comment]
@aarani do you mind fixing the conflicts, and adding this to the README file: https://github.com/nblockchain/TgSharp/pull/5#issuecomment-608401517

**Comment by knocte** [comment]
> @aarani do you mind fixing the conflicts, and adding this to the README file: #5 (comment)

ping

**Comment by solarin** [comment]
Telegram requests to change DC, the software tries to do it -->

> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
>    at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
>    at System.IO.BinaryReader.ReadInt64()
>    at TgSharp.Core.Network.MtProtoPlainSender.<Receive>d__6.MoveNext() in \TgSharp\src\TgSharp.Core\Network\MtProtoPlainSender.cs:line 51
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at TgSharp.Core.Auth.Authenticator.<DoAuthentication>d__0.MoveNext() in \TgSharp\src\TgSharp.Core\Auth\Authenticator.cs:line 39
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at TgSharp.Core.TelegramClient.<ConnectAsync>d__12.MoveNext() in \TgSharp\src\TgSharp.Core\TelegramClient.cs:line 90
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at TgSharp.Core.TelegramClient.<ReconnectToDcAsync>d__13.MoveNext() in \TgSharp\src\TgSharp.Core\TelegramClient.cs:line 155
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at TgSharp.Core.TelegramClient.<RequestWithDcMigration>d__14.MoveNext() in \TgSharp\src\TgSharp.Core\TelegramClient.cs:line 187
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at TgSharp.Core.TelegramClient.<SendCodeRequestAsync>d__16.MoveNext() in \TgSharp\src\TgSharp.Core\TelegramClient.cs:line 206
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at GroupCasher.GroupManager.<CheckClientConnected>d__17.MoveNext() in source\repos\GroupCasher\GroupCasher\GroupManager.cs:line 142
>

**Comment by solarin** [comment]
this is happening with my Emirati number, i can give it to you for testing purposes

**Comment by knocte** [comment]
@aarani how can a layer update cause transport/connection issues?

**Comment by aarani** [comment]
@solarin have you changed any codes?
@sochix it can't afaik and i tested dc switch it worked properly

**Comment by aarani** [comment]
@solarin have you changed any codes? maybe some connection issue? do you use something like vpn or proxy of some sort?
@knocte it can't afaik and i tested dc switch it worked properly

**Comment by knocte** [comment]
@aarani turns out Mario (@solarin) has told me that this connection issue is only happening for him for his number from Dubai, but doesn't happen with others (e.g. Vietnamese). He seems to be willing to give you the code so you can debug on your side

**Comment by solarin** [comment]
> @solarin have you changed any codes? maybe some connection issue? do you use something like vpn or proxy of some sort?
> @knocte it can't afaik and i tested dc switch it worked properly

no, i did not.

but honestly i didn't try if the problem also exists with layer66. let me see. sorry

**Comment by solarin** [comment]
this problem also exists in TLSharp. i'm opening it here: https://github.com/sochix/TLSharp/issues/935

**Comment by knocte** [comment]
Sigh. So then there's no blocker to get this in, right? does it work well for you?

**Comment by solarin** [comment]
i think it’s ok, i have been running for almost 12 hours

**Comment by knocte** [comment]
@aarani @solarin FYI I have rebased this PR

**Comment by sochix** [comment]
@aarani I didn't change anything. Good work, by the way!

**Comment by aarani** [comment]
> @aarani I didn't change anything. Good work, by the way!

thanks man, sorry, wrong mention.

**Comment by studasd** [comment]
Hey.
Is it possible to implement Two-factor authentication on the last layer?
The password verification algorithm has become more complicated after layer 66.

**Comment by aarani** [comment]
@knocte Please push this already and just create a legacy branch for 2FA Users

**Comment by aarani** [comment]
> Hey.
> Is it possible to implement Two-factor authentication on the last layer?
> The password verification algorithm has become more complicated after layer 66.

That will be on roadmap as soon as this pr get merged

**Comment by knocte** [comment]
> create a legacy branch for 2FA Users

Well, let's consider TLSharp the legacy branch? I'm not doing fixes to that repo anymore.

**Comment by knocte** [comment]
>  Please push this already

I'm not comfortable pushing this if the generator is not in sync with what is being generated here, I'm trying to understand why, first.

**Comment by aarani** [comment]
> > Please push this already
> 
> I'm not comfortable pushing this if the generator is not in sync with what is being generated here, I'm trying to understand why, first.

Have fun

**Comment by knocte** [comment]
Superseded by https://github.com/nblockchain/TgSharp/pull/13 , sorry for the long delay!

**Comment by ahmedibrahimsaadmostafa** [comment]
How I can login after registration? I want login after close my windows app. By which method I can check in session file? this is my code

**Pull request closed without merging**
