### PR TITLE
Core: allow reconnecting same TelegramClient instance

### PR DESCRIPTION
**Pull request by knocte**
Fixes https://github.com/sochix/TLSharp/issues/930

### CODE REVIEW

**Comment by knocte** [comment]
@solarin does it look good?

**Comment by solarin** [comment]
it's good bro, shoot ;)

**Comment by knocte** [comment]
@solarin does this also fix the `IsConnected` bug?

**Comment by solarin** [comment]
i will re-verify it today

**Comment by studasd** [comment]
Hey.
Is it possible to implement Two-factor authentication on the last layer?
The password verification algorithm has become more complicated after layer 66.

**Comment by knocte** [comment]
> how can test it? You mean add those changes in library by myself ?

hey, no, we just mean install TgSharp, but, what version did you install? you have to install the pre-release, not the latest release.

**Pull request merged**
